#!/bin/sh
node blink-led
node configure-and-check-input
node configure-and-check-output
node many-interrupts
node performance-async
node performance-sync
sleep 1
node wait-for-interrupt
sleep 1
node wait-for-many-interrupts

