#!/bin/sh
sudo $(which node) blink-led
sudo $(which node) configure-and-check-input
sudo $(which node) configure-and-check-output
sudo $(which node) many-interrupts
sudo $(which node) performance-async
sudo $(which node) performance-sync
sudo $(which node) wait-for-interrupt
sudo $(which node) wait-for-many-interrupts

