#!/bin/sh
sudo node blink-led
sudo node configure-and-check-input
sudo node configure-and-check-output
sudo node many-interrupts
sudo node performance-async
sudo node performance-sync
sudo node wait-for-interrupt
sudo node wait-for-many-interrupts

